import Footer from "@/components/Footer/page";
// import Header from "@/components/Header/page";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthRouter({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html
          lang="en"
          className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
          <body className="min-h-screen flex flex-col">
            <main className="flex-1">{children}</main>
            <Footer />
          </body>
        </html>
  );
}
